apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: catdog905/dev-ops-course-app-python:lab4
        env:
        - name: TEST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
        ports:
        - containerPort: 80

