apiVersion: v1
kind: Service
metadata:
  name: app-python
  namespace: default
  labels:
    app: app-python
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:    
    app: app-python
  type: NodePort
