---
- name: Deploy app_python
  hosts: all
  become: true
  roles:
    - web_app
  vars:
    app_dir: app_python
    app_image: catdog905/dev-ops-terraform-exercize-app-python:lab5
    web_port: 80
    web_app_full_wipe: true
