global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090

  - job_name: app_python
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - app_python:80

  - job_name: loki
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - loki:3100

  - job_name: promtail
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - promtail:9000

  - job_name: grafana
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - grafana:3000
